[toolchain]
anchor_version = "1.0.1"
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
brokex-core = "7DPzhH46ojNiQLfrQMZ3CTpBQR6mGAzzGvEUVMwEPNMy"
brokex-vault = "4fgPnwcAxYT3QAutMSLPMNczp4fPugTZYotdmZGsy6sR"

[programs.localnet]
brokex-vault = "4fgPnwcAxYT3QAutMSLPMNczp4fPugTZYotdmZGsy6sR"
brokex_core = "6Ymggvkuy7Yw4TvnjMKfMw1DCs9oguKrQfVzvHSyMP4S"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"


[hooks]
